ALTER TABLE "Garment" ADD COLUMN "favorite" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Pose" ADD COLUMN "favorite" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Outfit" ADD COLUMN "favorite" BOOLEAN NOT NULL DEFAULT false;
